<a href="https://colab.research.google.com/github/DiwakarBasnet/Neural_Network/blob/main/Sales_Prediction/Function_Sales_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Big Mart Sales Prediction
-> Multilayer Perceptron (MLP)

In [1]:
# importing required libraries
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# reading dataset
train_data = 'https://raw.githubusercontent.com/DiwakarBasnet/Neural_Network/main/Sales_Prediction/train_file.csv'
dataset1 = pd.read_csv(train_data, skipinitialspace=True)

test_data = 'https://raw.githubusercontent.com/DiwakarBasnet/Neural_Network/main/Sales_Prediction/test_file.csv'
dataset2 = pd.read_csv(test_data, skipinitialspace=True)

##1.Data Preprocessing

In [3]:
dataset1.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [4]:
# checking missing values in table
print(dataset1.isnull().sum(),"\n")
print(dataset2.isnull().sum())

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

Item_Identifier                 0
Item_Weight                   976
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  1606
Outlet_Location_Type            0
Outlet_Type                     0
dtype: int64

In [5]:
dataset1.dtypes

Item_Identifier               object
Item_Weight                  float64
Item_Fat_Content              object
Item_Visibility              float64
Item_Type                     object
Item_MRP                     float64
Outlet_Identifier             object
Outlet_Establishment_Year      int64
Outlet_Size                   object
Outlet_Location_Type          object
Outlet_Type                   object
Item_Outlet_Sales            float64
dtype: object

In [6]:
def converter(dataset):
  # filling missing values
  dataset['Item_Weight'].fillna(dataset['Item_Weight'].mean(), inplace=True)
  dataset['Outlet_Size'].fillna(dataset['Outlet_Size'].mode()[0], inplace=True)
  
  # converting categorical data to numbers
  dataset['Item_Fat_Content'] = dataset['Item_Fat_Content'].map({'LF':0, 'Low Fat':0, 'low fat':0, 'Regular':1, 'reg':1})
  
  dummy_Item_Type = pd.get_dummies(dataset.Item_Type)
  dummy_Outlet_Establishment_Year = pd.get_dummies(dataset.Outlet_Establishment_Year)
  dummy_Outlet_Size = pd.get_dummies(dataset.Outlet_Size)
  dummy_Outlet_Location_Type = pd.get_dummies(dataset.Outlet_Location_Type)
  dummy_Outlet_Type = pd.get_dummies(dataset.Outlet_Type)

  new_dataset = pd.concat([dataset.Item_Weight, dataset.Item_Fat_Content, dataset.Item_Visibility, dummy_Item_Type, dataset.Item_MRP,
                           dummy_Outlet_Establishment_Year, dummy_Outlet_Size, dummy_Outlet_Location_Type,
                           dummy_Outlet_Type], axis='columns')
  
  # normalizing dataset
  for i in new_dataset.columns[0:]:
    new_dataset[i] = (new_dataset[i] - new_dataset[i].min()) / (new_dataset[i].max() - new_dataset[i].min())

  return new_dataset

In [7]:
# storing all the features as X
X = converter(dataset1)
# storing target as y
y = dataset1['Item_Outlet_Sales']
# shape of X and y
X.shape, y.shape

((8523, 39), (8523,))

In [8]:
##### creating training and validation set #####
# random state to regenerate same train and validation set
# test size 0.2 will keep 20% data in validation and 80% train set

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=10, test_size=0.2)

(X_train.shape, y_train.shape), (X_test.shape, y_test.shape)

(((6818, 39), (6818,)), ((1705, 39), (1705,)))

##2.Defining the architecture of model

In [9]:
import keras
import tensorflow as tf
from keras import regularizers
from keras import backend as K
from keras.models import Sequential
from keras.layers import InputLayer, Dense

In [10]:
# defining input neurons
input_neurons = X_train.shape[1]
# defining output neurons
output_neurons = 1
# defining hidden layers and neurons in each layer
num_of_hidden_layers = 3
neuron_hidden_layer_1 = 30
neuron_hidden_layer_2 = 15
neuron_hidden_layer_3 = 5

In [11]:
from logging import INFO
model = Sequential()
model.add(InputLayer(input_shape=(input_neurons,)))
model.add(Dense(units=neuron_hidden_layer_1, activation='relu'))
model.add(Dense(units=neuron_hidden_layer_2, activation='relu'))
model.add(Dense(units=neuron_hidden_layer_3, activation='relu'))
model.add(Dense(units=output_neurons, activation='linear'))

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 30)                1200

 dense_1 (Dense)             (None, 15)                465

 dense_2 (Dense)             (None, 5)                 80

 dense_3 (Dense)             (None, 1)                 6

=================================================================
Total params: 1,751
Trainable params: 1,751
Non-trainable params: 0
_________________________________________________________________

In [13]:
def root_mean_squared_error(y_true, y_pred):
  return K.sqrt(K.mean(K.square(y_pred - y_true))) 

##### Compiling the model #####
model.compile(loss=root_mean_squared_error, optimizer='adam', metrics=['mean_squared_error'])

##3.Train model

In [14]:
model_history = model.fit(X_train, y_train, batch_size=128, validation_data=(X_test, y_test), epochs=100)

Epoch 1/100
54/54 [==============================] - 2s 15ms/step - loss: 2755.4773 - mean_squared_error: 7627101.0000 - val_loss: 2793.4465 - val_mean_squared_error: 7824225.0000
Epoch 2/100
54/54 [==============================] - 0s 6ms/step - loss: 2750.8809 - mean_squared_error: 7600613.0000 - val_loss: 2781.7642 - val_mean_squared_error: 7759133.5000
Epoch 3/100
54/54 [==============================] - 0s 6ms/step - loss: 2721.3711 - mean_squared_error: 7453442.0000 - val_loss: 2730.8342 - val_mean_squared_error: 7478535.5000
Epoch 4/100
54/54 [==============================] - 0s 7ms/step - loss: 2634.3579 - mean_squared_error: 6967546.5000 - val_loss: 2585.8743 - val_mean_squared_error: 6708268.0000
Epoch 5/100
54/54 [==============================] - 0s 5ms/step - loss: 2419.9070 - mean_squared_error: 5877363.0000 - val_loss: 2282.3555 - val_mean_squared_error: 5231541.0000
Epoch 6/100
54/54 [==============================] - 0s 6ms/step - loss: 2040.9299 - mean_squared_error: 4216247.0000 - val_loss: 1852.6510 - val_mean_squared_error: 3454809.2500
Epoch 7/100
54/54 [==============================] - 0s 6ms/step - loss: 1687.8607 - mean_squared_error: 2871334.7500 - val_loss: 1620.8239 - val_mean_squared_error: 2645495.2500
Epoch 8/100
54/54 [==============================] - 0s 6ms/step - loss: 1578.5638 - mean_squared_error: 2510191.0000 - val_loss: 1582.2217 - val_mean_squared_error: 2519527.0000
Epoch 9/100
54/54 [==============================] - 0s 6ms/step - loss: 1550.5551 - mean_squared_error: 2425137.2500 - val_loss: 1557.9243 - val_mean_squared_error: 2442725.0000
Epoch 10/100
54/54 [==============================] - 0s 6ms/step - loss: 1529.6659 - mean_squared_error: 2353195.7500 - val_loss: 1534.7495 - val_mean_squared_error: 2370394.0000
Epoch 11/100
54/54 [==============================] - 0s 6ms/step - loss: 1505.9242 - mean_squared_error: 2285233.0000 - val_loss: 1511.9208 - val_mean_squared_error: 2300045.5000
Epoch 12/100
54/54 [==============================] - 0s 6ms/step - loss: 1484.3066 - mean_squared_error: 2220190.0000 - val_loss: 1490.3324 - val_mean_squared_error: 2234588.0000
Epoch 13/100
54/54 [==============================] - 0s 5ms/step - loss: 1463.9651 - mean_squared_error: 2157659.5000 - val_loss: 1468.5508 - val_mean_squared_error: 2169660.5000
Epoch 14/100
54/54 [==============================] - 0s 6ms/step - loss: 1442.2150 - mean_squared_error: 2094928.2500 - val_loss: 1446.4728 - val_mean_squared_error: 2104861.2500
Epoch 15/100
54/54 [==============================] - 0s 8ms/step - loss: 1418.4032 - mean_squared_error: 2032356.1250 - val_loss: 1424.4221 - val_mean_squared_error: 2041117.7500
Epoch 16/100
54/54 [==============================] - 0s 5ms/step - loss: 1399.5867 - mean_squared_error: 1971260.1250 - val_loss: 1401.5815 - val_mean_squared_error: 1975860.1250
Epoch 17/100
54/54 [==============================] - 0s 6ms/step - loss: 1378.9139 - mean_squared_error: 1912092.7500 - val_loss: 1380.4113 - val_mean_squared_error: 1916618.1250
Epoch 18/100
54/54 [==============================] - 0s 7ms/step - loss: 1356.7356 - mean_squared_error: 1854911.6250 - val_loss: 1359.2097 - val_mean_squared_error: 1858162.5000
Epoch 19/100
54/54 [==============================] - 0s 5ms/step - loss: 1337.0236 - mean_squared_error: 1799978.7500 - val_loss: 1338.4149 - val_mean_squared_error: 1801384.0000
Epoch 20/100
54/54 [==============================] - 0s 6ms/step - loss: 1317.1970 - mean_squared_error: 1749021.3750 - val_loss: 1319.4956 - val_mean_squared_error: 1751154.5000
Epoch 21/100
54/54 [==============================] - 0s 7ms/step - loss: 1300.6726 - mean_squared_error: 1701506.5000 - val_loss: 1301.2487 - val_mean_squared_error: 1703112.1250
Epoch 22/100
54/54 [==============================] - 0s 6ms/step - loss: 1281.3011 - mean_squared_error: 1656202.3750 - val_loss: 1283.4291 - val_mean_squared_error: 1656577.0000
Epoch 23/100
54/54 [==============================] - 0s 6ms/step - loss: 1265.9415 - mean_squared_error: 1614117.8750 - val_loss: 1267.2650 - val_mean_squared_error: 1615440.1250
Epoch 24/100
54/54 [==============================] - 0s 6ms/step - loss: 1248.3856 - mean_squared_error: 1573573.5000 - val_loss: 1251.1926 - val_mean_squared_error: 1574029.7500
Epoch 25/100
54/54 [==============================] - 0s 6ms/step - loss: 1233.3375 - mean_squared_error: 1535991.8750 - val_loss: 1233.9688 - val_mean_squared_error: 1531422.8750
Epoch 26/100
54/54 [==============================] - 0s 6ms/step - loss: 1218.7872 - mean_squared_error: 1498380.2500 - val_loss: 1219.4761 - val_mean_squared_error: 1496029.1250
Epoch 27/100
54/54 [==============================] - 0s 6ms/step - loss: 1204.3689 - mean_squared_error: 1461841.5000 - val_loss: 1204.6775 - val_mean_squared_error: 1459989.8750
Epoch 28/100
54/54 [==============================] - 0s 5ms/step - loss: 1188.5625 - mean_squared_error: 1426653.1250 - val_loss: 1188.8726 - val_mean_squared_error: 1421417.0000
Epoch 29/100
54/54 [==============================] - 0s 7ms/step - loss: 1174.9196 - mean_squared_error: 1393670.2500 - val_loss: 1175.6151 - val_mean_squared_error: 1390606.0000
Epoch 30/100
54/54 [==============================] - 0s 5ms/step - loss: 1162.3314 - mean_squared_error: 1362697.6250 - val_loss: 1160.9326 - val_mean_squared_error: 1355796.8750
Epoch 31/100
54/54 [==============================] - 0s 6ms/step - loss: 1150.2109 - mean_squared_error: 1333261.8750 - val_loss: 1147.9349 - val_mean_squared_error: 1325458.3750
Epoch 32/100
54/54 [==============================] - 0s 8ms/step - loss: 1138.2015 - mean_squared_error: 1306531.8750 - val_loss: 1137.3146 - val_mean_squared_error: 1301637.3750
Epoch 33/100
54/54 [==============================] - 0s 9ms/step - loss: 1130.6494 - mean_squared_error: 1285860.1250 - val_loss: 1126.7102 - val_mean_squared_error: 1277539.1250
Epoch 34/100
54/54 [==============================] - 0s 7ms/step - loss: 1119.9070 - mean_squared_error: 1264269.7500 - val_loss: 1118.1182 - val_mean_squared_error: 1257984.8750
Epoch 35/100
54/54 [==============================] - 0s 8ms/step - loss: 1112.4196 - mean_squared_error: 1247234.8750 - val_loss: 1110.7517 - val_mean_squared_error: 1241488.8750
Epoch 36/100
54/54 [==============================] - 0s 6ms/step - loss: 1106.1858 - mean_squared_error: 1233761.5000 - val_loss: 1104.8059 - val_mean_squared_error: 1228131.2500
Epoch 37/100
54/54 [==============================] - 0s 7ms/step - loss: 1101.3286 - mean_squared_error: 1222878.5000 - val_loss: 1100.9988 - val_mean_squared_error: 1219509.1250
Epoch 38/100
54/54 [==============================] - 0s 7ms/step - loss: 1097.5530 - mean_squared_error: 1215012.6250 - val_loss: 1097.3477 - val_mean_squared_error: 1211468.5000
Epoch 39/100
54/54 [==============================] - 0s 7ms/step - loss: 1095.3165 - mean_squared_error: 1208842.5000 - val_loss: 1092.9423 - val_mean_squared_error: 1202287.8750
Epoch 40/100
54/54 [==============================] - 0s 5ms/step - loss: 1092.1558 - mean_squared_error: 1204317.6250 - val_loss: 1091.1879 - val_mean_squared_error: 1198421.0000
Epoch 41/100
54/54 [==============================] - 0s 8ms/step - loss: 1091.5740 - mean_squared_error: 1200227.7500 - val_loss: 1089.6213 - val_mean_squared_error: 1194923.3750
Epoch 42/100
54/54 [==============================] - 0s 7ms/step - loss: 1089.1078 - mean_squared_error: 1197541.6250 - val_loss: 1088.8652 - val_mean_squared_error: 1193125.6250
Epoch 43/100
54/54 [==============================] - 0s 7ms/step - loss: 1088.8907 - mean_squared_error: 1194350.0000 - val_loss: 1087.8771 - val_mean_squared_error: 1191396.7500
Epoch 44/100
54/54 [==============================] - 0s 5ms/step - loss: 1088.0063 - mean_squared_error: 1195485.8750 - val_loss: 1087.6733 - val_mean_squared_error: 1190491.8750
Epoch 45/100
54/54 [==============================] - 0s 5ms/step - loss: 1087.7832 - mean_squared_error: 1192686.6250 - val_loss: 1085.8492 - val_mean_squared_error: 1186830.0000
Epoch 46/100
54/54 [==============================] - 0s 7ms/step - loss: 1086.8911 - mean_squared_error: 1192517.3750 - val_loss: 1085.7258 - val_mean_squared_error: 1186242.6250
Epoch 47/100
54/54 [==============================] - 0s 8ms/step - loss: 1087.4946 - mean_squared_error: 1191630.6250 - val_loss: 1085.2605 - val_mean_squared_error: 1185384.0000
Epoch 48/100
54/54 [==============================] - 0s 5ms/step - loss: 1087.0741 - mean_squared_error: 1190655.5000 - val_loss: 1084.4656 - val_mean_squared_error: 1183637.8750
Epoch 49/100
54/54 [==============================] - 0s 5ms/step - loss: 1086.5563 - mean_squared_error: 1190554.1250 - val_loss: 1083.8324 - val_mean_squared_error: 1182301.5000
Epoch 50/100
54/54 [==============================] - 0s 7ms/step - loss: 1087.1624 - mean_squared_error: 1189350.6250 - val_loss: 1083.2123 - val_mean_squared_error: 1180979.2500
Epoch 51/100
54/54 [==============================] - 0s 6ms/step - loss: 1085.7786 - mean_squared_error: 1190558.5000 - val_loss: 1083.6561 - val_mean_squared_error: 1181919.8750
Epoch 52/100
54/54 [==============================] - 0s 6ms/step - loss: 1086.2676 - mean_squared_error: 1189745.0000 - val_loss: 1083.4343 - val_mean_squared_error: 1181503.2500
Epoch 53/100
54/54 [==============================] - 0s 6ms/step - loss: 1085.6460 - mean_squared_error: 1189889.6250 - val_loss: 1084.0377 - val_mean_squared_error: 1182581.7500
Epoch 54/100
54/54 [==============================] - 0s 6ms/step - loss: 1086.5441 - mean_squared_error: 1189423.6250 - val_loss: 1083.9644 - val_mean_squared_error: 1182340.5000
Epoch 55/100
54/54 [==============================] - 0s 5ms/step - loss: 1085.6682 - mean_squared_error: 1188873.3750 - val_loss: 1083.0741 - val_mean_squared_error: 1180901.6250
Epoch 56/100
54/54 [==============================] - 0s 5ms/step - loss: 1087.8579 - mean_squared_error: 1189423.2500 - val_loss: 1082.1665 - val_mean_squared_error: 1178731.0000
Epoch 57/100
54/54 [==============================] - 0s 6ms/step - loss: 1085.5712 - mean_squared_error: 1189596.1250 - val_loss: 1083.5341 - val_mean_squared_error: 1181430.7500
Epoch 58/100
54/54 [==============================] - 0s 5ms/step - loss: 1086.8347 - mean_squared_error: 1190386.0000 - val_loss: 1082.2180 - val_mean_squared_error: 1178737.2500
Epoch 59/100
54/54 [==============================] - 0s 6ms/step - loss: 1086.3257 - mean_squared_error: 1189063.2500 - val_loss: 1082.1476 - val_mean_squared_error: 1178638.6250
Epoch 60/100
54/54 [==============================] - 0s 7ms/step - loss: 1086.0756 - mean_squared_error: 1187993.7500 - val_loss: 1081.4790 - val_mean_squared_error: 1177218.0000
Epoch 61/100
54/54 [==============================] - 0s 5ms/step - loss: 1086.6716 - mean_squared_error: 1188499.5000 - val_loss: 1081.3840 - val_mean_squared_error: 1176994.0000
Epoch 62/100
54/54 [==============================] - 1s 11ms/step - loss: 1084.4661 - mean_squared_error: 1187573.5000 - val_loss: 1081.6115 - val_mean_squared_error: 1177412.5000
Epoch 63/100
54/54 [==============================] - 0s 7ms/step - loss: 1085.2852 - mean_squared_error: 1188246.1250 - val_loss: 1083.0157 - val_mean_squared_error: 1180276.0000
Epoch 64/100
54/54 [==============================] - 0s 6ms/step - loss: 1083.6842 - mean_squared_error: 1188088.2500 - val_loss: 1082.2679 - val_mean_squared_error: 1178672.7500
Epoch 65/100
54/54 [==============================] - 0s 4ms/step - loss: 1085.9874 - mean_squared_error: 1188518.8750 - val_loss: 1082.7651 - val_mean_squared_error: 1179735.3750
Epoch 66/100
54/54 [==============================] - 0s 5ms/step - loss: 1086.1735 - mean_squared_error: 1188132.3750 - val_loss: 1082.3058 - val_mean_squared_error: 1178779.3750
Epoch 67/100
54/54 [==============================] - 0s 5ms/step - loss: 1084.5769 - mean_squared_error: 1188256.0000 - val_loss: 1081.9567 - val_mean_squared_error: 1178608.5000
Epoch 68/100
54/54 [==============================] - 0s 6ms/step - loss: 1086.3438 - mean_squared_error: 1188435.2500 - val_loss: 1081.1729 - val_mean_squared_error: 1176525.5000
Epoch 69/100
54/54 [==============================] - 0s 9ms/step - loss: 1084.7760 - mean_squared_error: 1186654.7500 - val_loss: 1081.4109 - val_mean_squared_error: 1176903.8750
Epoch 70/100
54/54 [==============================] - 0s 7ms/step - loss: 1081.8232 - mean_squared_error: 1187080.7500 - val_loss: 1080.9103 - val_mean_squared_error: 1176044.3750
Epoch 71/100
54/54 [==============================] - 0s 6ms/step - loss: 1085.2285 - mean_squared_error: 1187289.3750 - val_loss: 1080.7931 - val_mean_squared_error: 1175700.2500
Epoch 72/100
54/54 [==============================] - 0s 3ms/step - loss: 1085.0490 - mean_squared_error: 1186981.3750 - val_loss: 1080.6365 - val_mean_squared_error: 1175360.2500
Epoch 73/100
54/54 [==============================] - 0s 3ms/step - loss: 1085.2068 - mean_squared_error: 1186132.6250 - val_loss: 1080.9240 - val_mean_squared_error: 1175939.2500
Epoch 74/100
54/54 [==============================] - 0s 3ms/step - loss: 1084.1346 - mean_squared_error: 1185715.2500 - val_loss: 1080.6740 - val_mean_squared_error: 1175378.6250
Epoch 75/100
54/54 [==============================] - 0s 3ms/step - loss: 1084.2446 - mean_squared_error: 1185326.3750 - val_loss: 1080.3401 - val_mean_squared_error: 1174731.7500
Epoch 76/100
54/54 [==============================] - 0s 3ms/step - loss: 1084.9441 - mean_squared_error: 1186045.3750 - val_loss: 1079.9410 - val_mean_squared_error: 1174073.3750
Epoch 77/100
54/54 [==============================] - 0s 3ms/step - loss: 1084.3921 - mean_squared_error: 1185581.3750 - val_loss: 1080.4059 - val_mean_squared_error: 1174937.2500
Epoch 78/100
54/54 [==============================] - 0s 3ms/step - loss: 1084.1471 - mean_squared_error: 1185302.5000 - val_loss: 1080.6326 - val_mean_squared_error: 1175269.2500
Epoch 79/100
54/54 [==============================] - 0s 3ms/step - loss: 1082.3539 - mean_squared_error: 1185296.5000 - val_loss: 1081.0962 - val_mean_squared_error: 1176219.3750
Epoch 80/100
54/54 [==============================] - 0s 3ms/step - loss: 1084.8474 - mean_squared_error: 1184633.5000 - val_loss: 1080.1620 - val_mean_squared_error: 1174612.3750
Epoch 81/100
54/54 [==============================] - 0s 3ms/step - loss: 1085.1365 - mean_squared_error: 1186555.7500 - val_loss: 1079.6549 - val_mean_squared_error: 1173453.7500
Epoch 82/100
54/54 [==============================] - 0s 3ms/step - loss: 1083.7732 - mean_squared_error: 1185513.0000 - val_loss: 1080.0553 - val_mean_squared_error: 1174180.5000
Epoch 83/100
54/54 [==============================] - 0s 3ms/step - loss: 1083.9104 - mean_squared_error: 1185368.8750 - val_loss: 1079.6084 - val_mean_squared_error: 1173258.2500
Epoch 84/100
54/54 [==============================] - 0s 3ms/step - loss: 1083.1263 - mean_squared_error: 1184688.7500 - val_loss: 1080.9486 - val_mean_squared_error: 1175848.3750
Epoch 85/100
54/54 [==============================] - 0s 3ms/step - loss: 1084.1349 - mean_squared_error: 1184082.0000 - val_loss: 1079.2783 - val_mean_squared_error: 1172455.2500
Epoch 86/100
54/54 [==============================] - 0s 3ms/step - loss: 1082.9940 - mean_squared_error: 1184909.2500 - val_loss: 1079.1598 - val_mean_squared_error: 1172349.1250
Epoch 87/100
54/54 [==============================] - 0s 3ms/step - loss: 1084.6012 - mean_squared_error: 1183713.3750 - val_loss: 1079.1858 - val_mean_squared_error: 1172287.5000
Epoch 88/100
54/54 [==============================] - 0s 3ms/step - loss: 1083.1127 - mean_squared_error: 1184304.0000 - val_loss: 1079.4178 - val_mean_squared_error: 1172711.2500
Epoch 89/100
54/54 [==============================] - 0s 3ms/step - loss: 1082.9299 - mean_squared_error: 1183977.8750 - val_loss: 1078.7900 - val_mean_squared_error: 1171548.0000
Epoch 90/100
54/54 [==============================] - 0s 3ms/step - loss: 1083.1808 - mean_squared_error: 1184007.7500 - val_loss: 1078.7284 - val_mean_squared_error: 1171405.1250
Epoch 91/100
54/54 [==============================] - 0s 3ms/step - loss: 1084.8546 - mean_squared_error: 1184133.1250 - val_loss: 1078.3997 - val_mean_squared_error: 1170636.3750
Epoch 92/100
54/54 [==============================] - 0s 3ms/step - loss: 1084.0214 - mean_squared_error: 1182916.2500 - val_loss: 1078.4038 - val_mean_squared_error: 1170536.2500
Epoch 93/100
54/54 [==============================] - 0s 3ms/step - loss: 1082.9110 - mean_squared_error: 1182403.7500 - val_loss: 1078.2910 - val_mean_squared_error: 1170399.2500
Epoch 94/100
54/54 [==============================] - 0s 3ms/step - loss: 1082.9194 - mean_squared_error: 1183158.8750 - val_loss: 1078.6865 - val_mean_squared_error: 1171495.3750
Epoch 95/100
54/54 [==============================] - 0s 3ms/step - loss: 1081.4673 - mean_squared_error: 1182543.5000 - val_loss: 1078.9435 - val_mean_squared_error: 1171681.0000
Epoch 96/100
54/54 [==============================] - 0s 3ms/step - loss: 1083.6188 - mean_squared_error: 1182260.8750 - val_loss: 1078.5172 - val_mean_squared_error: 1170879.1250
Epoch 97/100
54/54 [==============================] - 0s 3ms/step - loss: 1082.5261 - mean_squared_error: 1182117.1250 - val_loss: 1079.7134 - val_mean_squared_error: 1173140.5000
Epoch 98/100
54/54 [==============================] - 0s 3ms/step - loss: 1082.4337 - mean_squared_error: 1182427.8750 - val_loss: 1078.4482 - val_mean_squared_error: 1170548.2500
Epoch 99/100
54/54 [==============================] - 0s 3ms/step - loss: 1083.1796 - mean_squared_error: 1181271.3750 - val_loss: 1078.0112 - val_mean_squared_error: 1169681.0000
Epoch 100/100
54/54 [==============================] - 0s 3ms/step - loss: 1083.3412 - mean_squared_error: 1181713.0000 - val_loss: 1077.7994 - val_mean_squared_error: 1169252.8750

In [15]:
from sklearn.metrics import r2_score
##### Evaluating model performance on validation set #####
prediction = model.predict(X_test)

# calculating the accuracy on validation set
r2_score(y_test, prediction)

0.6061015252727734

In [16]:
##### Test data preprocessing #####
X_check = converter(dataset2)
X_check.head()

,Item_Weight,Item_Fat_Content,Item_Visibility,Baking Goods,Breads,Breakfast,Canned,Dairy,Frozen Foods,Fruits and Vegetables,...,High,Medium,Small,Tier 1,Tier 2,Tier 3,Grocery Store,Supermarket Type1,Supermarket Type2,Supermarket Type3
0,0.964275,0.0,0.023374,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.222983,1.0,0.118737,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,0.598095,0.0,0.307674,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
3,0.164335,0.0,0.047548,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
4,0.484706,1.0,0.366458,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [17]:
pred = model.predict(X_check)

In [18]:
submission = pd.DataFrame()
submission['Item_Identifier'] = dataset2['Item_Identifier']
submission['Outlet_Identifier'] = dataset2['Outlet_Identifier']
submission['Item_Outlet_Sales']= pred

submission

     Item_Identifier Outlet_Identifier  Item_Outlet_Sales
0              FDW58            OUT049        1735.224609
1              FDW14            OUT017        1361.988281
2              NCN55            OUT010         972.650635
3              FDQ58            OUT017        2573.057129
4              FDY38            OUT027        5355.310059
...              ...               ...                ...
5676           FDB58            OUT046        2246.198730
5677           FDD47            OUT018        2513.771729
5678           NCO17            OUT045        1740.460693
5679           FDJ26            OUT017        3728.037109
5680           FDU37            OUT045        1196.488159

[5681 rows x 3 columns]

In [19]:
submission.to_csv('solution.csv', index=False)